#!/usr/bin/env python3
"""
Daily random scheduler for TechNieuwsVandaag.
Run once at midnight to set that day's 5 article slots.
Generates random times between 07:00-19:00 CET with
minimum 90 minute gaps between runs.
"""

import os
import random
import subprocess
from datetime import datetime, date
from zoneinfo import ZoneInfo

PYTHON = "/home/dgebbink/projects/technieuwsvandaag/venv/bin/python3"


def generate_random_times(
    n: int = 5,
    start_hour: int = 7,
    end_hour: int = 19,
    min_gap_minutes: int = 90,
) -> list[tuple[int, int]]:
    """Generates n random CET times within the given window.
    Pre:  (end_hour - start_hour) * 60 >= n * min_gap_minutes
    Post: sorted list of (hour, minute) tuples in CET,
          every pair at least min_gap_minutes apart
    """
    window = (end_hour - start_hour) * 60
    times: list[tuple[int, int]] = []
    attempts = 0

    while len(times) < n and attempts < 2000:
        attempts += 1
        offset = random.randint(0, window)
        h = start_hour + offset // 60
        m = offset % 60

        too_close = any(
            abs((h * 60 + m) - (eh * 60 + em)) < min_gap_minutes
            for eh, em in times
        )
        if not too_close:
            times.append((h, m))

    return sorted(times)


def cet_to_utc(
    times_cet: list[tuple[int, int]],
) -> list[tuple[int, int]]:
    """Converts CET/CEST times to UTC.
    Pre:  times_cet contains valid (hour, minute) tuples
    Post: returns UTC equivalents, DST-aware via zoneinfo
    """
    tz  = ZoneInfo("Europe/Amsterdam")
    utc = ZoneInfo("UTC")
    today = date.today()
    result = []

    for h, m in times_cet:
        dt_local = datetime(
            today.year, today.month, today.day, h, m,
            tzinfo=tz,
        )
        dt_utc = dt_local.astimezone(utc)
        result.append((dt_utc.hour, dt_utc.minute))

    return result


def build_crontab(
    project_path: str,
    utc_times: list[tuple[int, int]],
    cet_times: list[tuple[int, int]],
) -> str:
    """Builds complete crontab string for today's schedule.
    Pre:  project_path is absolute; both time lists same length
    Post: returns crontab string with all recurring and
          daily-random jobs included
    """
    lines = [
        "# Edit this file to introduce tasks to be run by cron.",
        "PATH=/usr/bin:/bin:/usr/local/bin:/home/dgebbink/.local/bin",
        "",
        "# Snake — static HTML game served on :8080",
        "@reboot cd /home/dgebbink/projects/snake && python3 -m http.server 8080 >> /home/dgebbink/projects/snake/snake.log 2>&1",
        "",
        "# TechNieuwsVandaag — auto-generated by scheduler.py",
        f"# Generated: {datetime.now().isoformat()}",
        "",
        "# Regenerate schedule daily at midnight UTC",
        f"0 0 * * * cd {project_path} && "
        f"{PYTHON} scheduler.py "
        f">> {project_path}/logs/scheduler.log 2>&1",
        "",
        "# Daily article runs (random CET times):",
    ]

    for i, ((uh, um), (ch, cm)) in enumerate(
        zip(utc_times, cet_times), 1
    ):
        lines.append(
            f"{um} {uh} * * * cd {project_path} && "
            f"{PYTHON} main.py "
            f">> {project_path}/logs/cron_run_{i}.log 2>&1"
            f"  # slot {i}: {ch:02d}:{cm:02d} CET"
        )

    # Log cleanup altijd om 00:00 UTC (vóór scheduler-regeneratie)
    lines += [
        "",
        "# Log cleanup om middernacht (vóór schema-regeneratie)",
        f"0 0 * * * cd {project_path} && "
        f"{PYTHON} log_cleaner.py "
        f">> {project_path}/logs/log_cleaner.log 2>&1",
    ]

    # Instagram-digest om 19:45 CET — bundelt de dagwachtrij tot één post,
    # ruim ná het laatste artikel-slot (uiterlijk 19:00) en vóór het
    # dagoverzicht, zodat die de post nog kan meenemen als hij dat ooit doet
    ig_digest_cet = (19, 45)
    ig_digest_utc = cet_to_utc([ig_digest_cet])[0]
    lines += [
        "",
        "# Instagram-digest om 19:45 CET (bundelt de dagartikelen tot 1 post)",
        f"{ig_digest_utc[1]} {ig_digest_utc[0]} * * * cd {project_path} && "
        f"{PYTHON} instagram_digest.py "
        f">> {project_path}/logs/cron_instagram_digest.log 2>&1",
    ]

    # Gecombineerd dagoverzicht om 20:00 CET (artikelen + Bluesky + tegoed)
    digest_cet = (20, 0)
    digest_utc = cet_to_utc([digest_cet])[0]
    lines += [
        "",
        "# Gecombineerd dagoverzicht om 20:00 CET (artikelen + Bluesky + tegoed)",
        f"{digest_utc[1]} {digest_utc[0]} * * * cd {project_path} && "
        f"{PYTHON} daily_digest.py "
        f">> {project_path}/logs/cron_digest.log 2>&1",
    ]

    # Service watchdog elke 5 minuten (herstart gestopte supervisor-services)
    lines += [
        "",
        "# Service watchdog (supervisor-services + log-permissies)",
        f"*/5 * * * * bash {project_path}/service_watchdog.sh "
        f">> {project_path}/logs/service_watchdog.log 2>&1",
    ]

    # Bronnenlijst wekelijks beargumenteerd uitbreiden (cross-linking + Claude-suggesties)
    lines += [
        "",
        "# Bronnenlijst wekelijks uitbreiden (zondag 04:00 UTC)",
        f"0 4 * * 0 cd {project_path} && "
        f"{PYTHON} source_discovery.py "
        f">> {project_path}/logs/source_discovery.log 2>&1",
    ]

    # Cultureel Amsterdam — self-healing scrape-stap. Draait 07:30 CEST (05:30 UTC),
    # ná de nacht-scrape (03:00) + resume (06:30). Staat hier omdat dit script de
    # workstation-crontab elke nacht overschrijft; zie amsterdam/heal_runner.py.
    _AMS = "/home/dgebbink/projects/amsterdam/backend/scrapers"
    lines += [
        "",
        "# Cultureel Amsterdam self-healing scrape-runner (07:30 CEST)",
        f"30 5 * * * cd {_AMS} && .venv/bin/python heal_runner.py "
        f">> {_AMS}/heal_runner.log 2>&1",
    ]

    return "\n".join(lines) + "\n"


def main() -> None:
    """Generates and installs today's random schedule.
    Pre:  script is in project root; logs/ dir exists
    Post: crontab updated with 5 random slots for today
          schedule written to logs/daily_schedule.log
    """
    project_path = os.path.dirname(os.path.abspath(__file__))
    os.makedirs(f"{project_path}/logs", exist_ok=True)

    cet_times = generate_random_times(
        n=5,
        start_hour=7,
        end_hour=19,
        min_gap_minutes=90,
    )
    utc_times = cet_to_utc(cet_times)

    cet_str = [f"{h:02d}:{m:02d}" for h, m in cet_times]
    print(f"Vandaag's schema (CET): {cet_str}")

    with open(f"{project_path}/logs/daily_schedule.log", "a") as f:
        f.write(f"{date.today().isoformat()} {cet_str}\n")

    crontab = build_crontab(project_path, utc_times, cet_times)

    proc = subprocess.run(
        ["crontab", "-"],
        input=crontab,
        text=True,
        capture_output=True,
    )

    if proc.returncode == 0:
        print("Crontab succesvol geïnstalleerd")
        subprocess.run(["crontab", "-l"])
    else:
        print(f"Crontab installatie mislukt: {proc.stderr}")


if __name__ == "__main__":
    main()
