#!/usr/bin/env python3
"""
Daily random scheduler for TechNieuwsVandaag.
Run once at midnight to set that day's 5 article slots.
Generates random times between 07:00-19:00 CET with
minimum 90 minute gaps between runs.
"""

import os
import random
import subprocess
from datetime import datetime, date

# config pint TZ op Europe/Amsterdam (zie daar) — importeer het vóór er ook maar
# één datum of tijd wordt berekend.
from config import PAUSED, REEL_CYCLE_DAYS, is_reel_day, next_reel_day

PYTHON = "/home/dgebbink/projects/technieuwsvandaag/venv/bin/python3"


def generate_random_times(
    n: int = 5,
    start_hour: int = 7,
    end_hour: int = 19,
    min_gap_minutes: int = 90,
) -> list[tuple[int, int]]:
    """Generates n random CET times within the given window.
    Pre:  (end_hour - start_hour) * 60 >= n * min_gap_minutes
    Post: sorted list of (hour, minute) tuples in CET,
          every pair at least min_gap_minutes apart
    """
    window = (end_hour - start_hour) * 60
    times: list[tuple[int, int]] = []
    attempts = 0

    while len(times) < n and attempts < 2000:
        attempts += 1
        offset = random.randint(0, window)
        h = start_hour + offset // 60
        m = offset % 60

        too_close = any(
            abs((h * 60 + m) - (eh * 60 + em)) < min_gap_minutes
            for eh, em in times
        )
        if not too_close:
            times.append((h, m))

    return sorted(times)


def build_crontab(
    project_path: str,
    cet_times: list[tuple[int, int]],
) -> str:
    """Builds complete crontab string for today's schedule.

    **Alle tijden staan hier in Amsterdam-tijd, zonder omrekening.** De daemon
    plant in die zone (geërfd uit zijn omgeving; `/etc/timezone` zegt misleidend
    `Etc/UTC`). Er heeft hier eerst een `cet_to_utc()` gestaan en daarna een
    `cet_to_cron_clock()` die de klok op runtime probeerde te detecteren — beide
    zetten élke job twee uur te vroeg. Die detectie kán niet werken: ze leest de
    tijdzone van het eigen proces, en cron geeft zijn TZ juist níét door aan
    jobs, dus die zagen UTC terwijl de daemon Amsterdam aanhield. Vandaar de
    `TZ=`-regel hieronder: die trekt de jobs gelijk met de planning, waarna
    omrekenen overbodig is. `CRON_TZ` is geen alternatief — cron 3.0pl1 negeert
    het (empirisch getest 2026-07-27).

    Pre:  project_path is absoluut; cet_times zijn (hour, minute)-tupels in
          Europe/Amsterdam
    Post: returns crontab string with all recurring and
          daily-random jobs included
    """
    lines = [
        "# Edit this file to introduce tasks to be run by cron.",
        "PATH=/usr/bin:/bin:/usr/local/bin:/home/dgebbink/.local/bin",
        "# Cron geeft zijn eigen TZ niet door aan jobs; zonder deze regel draaien",
        "# ze op /etc/localtime (Etc/UTC) terwijl de daemon in Amsterdam plant.",
        "TZ=Europe/Amsterdam",
        "",
        "# Snake — static HTML game served on :8080",
        "@reboot cd /home/dgebbink/projects/snake && python3 -m http.server 8080 >> /home/dgebbink/projects/snake/snake.log 2>&1",
        "",
        "# TechNieuwsVandaag — auto-generated by scheduler.py",
        f"# Generated: {datetime.now().isoformat()}",
        "",
        "# Regenerate schedule daily at midnight CET",
        f"0 0 * * * cd {project_path} && "
        f"{PYTHON} scheduler.py "
        f">> {project_path}/logs/scheduler.log 2>&1",
        "",
    ]

    if PAUSED:
        lines += [
            "# ---------------------------------------------------------------",
            "# TNV_PAUSED=true in .env — alle contentregels (main.py, editorial,",
            "# Instagram-digest, Reel) zijn hieronder weggelaten. Zet de vlag uit",
            "# en draai scheduler.py om ze terug te zetten.",
            "# ---------------------------------------------------------------",
        ]
    else:
        lines += ["# Daily article runs (random CET times):"]
        for i, (h, m) in enumerate(cet_times, 1):
            lines.append(
                f"{m} {h} * * * cd {project_path} && "
                f"{PYTHON} main.py "
                f">> {project_path}/logs/cron_run_{i}.log 2>&1"
                f"  # slot {i}: {h:02d}:{m:02d} CET"
            )

    # Log cleanup altijd om 00:00 cron-klok (vóór scheduler-regeneratie)
    lines += [
        "",
        "# Log cleanup om middernacht (vóór schema-regeneratie)",
        f"0 0 * * * cd {project_path} && "
        f"{PYTHON} log_cleaner.py "
        f">> {project_path}/logs/log_cleaner.log 2>&1",
    ]

    # Instagram-digest om 19:45 CET — bundelt de dagwachtrij tot één post,
    # ruim ná het laatste artikel-slot (uiterlijk 19:00) en vóór het
    # dagoverzicht, zodat die de post nog kan meenemen als hij dat ooit doet
    if not PAUSED:
        lines += [
            "",
            "# Instagram-digest om 19:45 CET (bundelt de dagartikelen tot 1 post)",
            f"45 19 * * * cd {project_path} && "
            f"{PYTHON} instagram_digest.py "
            f">> {project_path}/logs/cron_instagram_digest.log 2>&1",
        ]

    # Instagram-Reel elke REEL_CYCLE_DAYS dagen (zie config.is_reel_day) om
    # 11:00 CET — silent 9:16-slideshow, zie INSTAGRAM_PLAN.md fase 7 en 10.
    # De regel staat alleen in de crontab op een cyclusdag; op andere dagen
    # ontbreekt hij gewoon. Daardoor kan de weekdag rouleren, wat met een
    # cron-veld niet uit te drukken is (day-of-month/6 springt per maand).
    if PAUSED:
        pass  # Reel-regel weggelaten, zie het pauzeblok hierboven
    elif is_reel_day():
        lines += [
            "",
            f"# Instagram-Reel vandaag om 11:00 CET (cyclus van {REEL_CYCLE_DAYS} dagen)",
            f"0 11 * * * cd {project_path} && "
            f"{PYTHON} weekly_reel.py "
            f">> {project_path}/logs/cron_weekly_reel.log 2>&1",
        ]
    else:
        lines += [
            "",
            f"# Geen Instagram-Reel vandaag — eerstvolgende: {next_reel_day().isoformat()}",
        ]

    # Gecombineerd dagoverzicht om 20:00 CET (artikelen + Bluesky + tegoed)
    lines += [
        "",
        "# Gecombineerd dagoverzicht om 20:00 CET (artikelen + Bluesky + Instagram + tegoed)",
        f"0 20 * * * cd {project_path} && "
        f"{PYTHON} daily_digest.py "
        f">> {project_path}/logs/cron_digest.log 2>&1",
    ]

    # Editorial op ma/wo/vr om 09:00 CET — opiniërend redactiestuk over een
    # onderwerp uit de artikelen van de afgelopen dagen. 's Ochtends zodat er
    # een werkdag overblijft om het concept te lezen; het gaat als draft naar
    # WordPress en wacht op de Publiceer-knop in de mail.
    if not PAUSED:
        lines += [
            "",
            "# Editorial op ma/wo/vr om 09:00 CET (draft + goedkeuringsmail)",
            f"0 9 * * 1,3,5 cd {project_path} && "
            f"{PYTHON} editorial.py "
            f">> {project_path}/logs/cron_editorial.log 2>&1",
        ]

    # Service watchdog elke 5 minuten (herstart gestopte supervisor-services)
    lines += [
        "",
        "# Service watchdog (supervisor-services + log-permissies)",
        f"*/5 * * * * bash {project_path}/service_watchdog.sh "
        f">> {project_path}/logs/service_watchdog.log 2>&1",
    ]

    # Cultureel Amsterdam — self-healing scrape-stap. Draait 07:30 CET, ná de
    # nacht-scrape (03:00) + resume (06:30). Stond op `30 5` omdat de tijd naar
    # UTC was omgerekend; met TZ=Europe/Amsterdam is dat 05:30 geworden en dus
    # te vroeg. Staat hier omdat dit script de workstation-crontab elke nacht
    # overschrijft; zie amsterdam/heal_runner.py.
    _AMS = "/home/dgebbink/projects/amsterdam/backend/scrapers"
    lines += [
        "",
        "# Cultureel Amsterdam self-healing scrape-runner (07:30 CET)",
        f"30 7 * * * cd {_AMS} && .venv/bin/python heal_runner.py "
        f">> {_AMS}/heal_runner.log 2>&1",
    ]

    return "\n".join(lines) + "\n"


def main() -> None:
    """Generates and installs today's random schedule.
    Pre:  script is in project root; logs/ dir exists
    Post: crontab updated with 5 random slots for today
          schedule written to logs/daily_schedule.log
    """
    project_path = os.path.dirname(os.path.abspath(__file__))
    os.makedirs(f"{project_path}/logs", exist_ok=True)

    if PAUSED:
        cet_times = []
        print(f"TNV_PAUSED=true — geen contentregels in de crontab ({date.today().isoformat()})")
    else:
        cet_times = generate_random_times(
            n=5,
            start_hour=7,
            end_hour=19,
            min_gap_minutes=90,
        )
    cet_str = [f"{h:02d}:{m:02d}" for h, m in cet_times]
    if not PAUSED:
        print(f"Vandaag ({date.today().isoformat()}) schema (CET): {cet_str}")
    print(f"Lokale klok van dit proces: {datetime.now().astimezone():%Y-%m-%d %H:%M %Z}")

    with open(f"{project_path}/logs/daily_schedule.log", "a") as f:
        f.write(f"{date.today().isoformat()} {'GEPAUZEERD' if PAUSED else cet_str}\n")

    crontab = build_crontab(project_path, cet_times)

    proc = subprocess.run(
        ["crontab", "-"],
        input=crontab,
        text=True,
        capture_output=True,
    )

    if proc.returncode == 0:
        print("Crontab succesvol geïnstalleerd")
        subprocess.run(["crontab", "-l"])
    else:
        print(f"Crontab installatie mislukt: {proc.stderr}")


if __name__ == "__main__":
    main()
